/*
 * lexer.h
 *
 * Copyright (C) 2026 Aerospike, Inc.
 *
 * Portions may be licensed to Aerospike, Inc. under one or more contributor
 * license agreements.
 *
 * This program is free software: you can redistribute it and/or modify it under
 * the terms of the GNU Affero General Public License as published by the Free
 * Software Foundation, either version 3 of the License, or (at your option) any
 * later version.
 *
 * This program is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Affero General Public License for more
 * details.
 *
 * You should have received a copy of the GNU Affero General Public License
 * along with this program.  If not, see http://www.gnu.org/licenses/
 */

#pragma once

#include <stdbool.h>
#include <stdint.h>

// Token IDs are defined by lemon in parser.h.
// The lexer returns those values.
// Special values: 0 = EOF, negative = error.
#define TOK_EOF 0
#define TOK_ERROR (-1)
#define TOK_ERROR_INT_RANGE (-2)
#define TOK_ERROR_UNCLOSED_STRING (-3)
#define TOK_ERROR_UNCLOSED_COMMENT (-4)
#define TOK_ERROR_BLOB_ODD_HEX (-5)
#define TOK_ERROR_FLOAT_RANGE (-6)
#define TOK_ERROR_RANGE_DOTS (-7)
#define TOK_ERROR_EXP_FLOAT (-8)
#define TOK_ERROR_LOGICAL_NOT (-9)
#define TOK_ERROR_B64_BAD_LEN (-10)
#define TOK_ERROR_UNCLOSED_REGEX (-11)

// Token IDs for grammar symbols come from parser.h (generated by lemon).

typedef struct token_value_u {
	// Source span of this token: byte offset into the input and byte length.
	// Set for EVERY token by lexer_next, so a grammar reduction can stamp the
	// precise span onto the AST node it builds -- without this, ast_new falls
	// back to pool->cur_offset, which by reduce time is the lookahead token.
	// Distinct from str.offset below, which is the string/blob *content* span
	// (excludes the surrounding quotes).
	uint32_t offset;
	uint32_t sz;
	union {
		int64_t ival;
		double fval;
		struct {
			uint32_t offset;
			uint32_t sz;
		} str;
		// TOK_REGEX: /pattern/flags. Only the two lengths are stored;
		// the offsets derive from this token's span (offset = the
		// opening slash): pattern = offset+1, flags = offset+pat_sz+2.
		// Reconstructed at the two TOK_REGEX rules in ael_parser.y.
		struct {
			uint32_t pat_sz;
			uint32_t flag_sz;
		} regex;
	};
} token_value;

typedef struct lexer_s {
	const char* start;
	const char* cursor;
	const char* limit;
	const char* marker;
	const char* token;
	uint32_t token_offset;
	uint32_t token_sz;
	// One-shot latch set right after `=~` (and after a `pattern:` named
	// arg -- regexReplace's regex operand): the next token, if it opens
	// with `/`, is a regex literal, not division. Confines the
	// `/`-disambiguation to the two positions where a regex is
	// grammatically legal. The "next char is `/`" guard in lexer_next
	// keeps false latches (e.g. `$.pattern:INT`) harmless.
	bool expect_regex;
	// True when the token just returned was the bare name `pattern`; a
	// following `:` arms expect_regex for regexReplace's pattern arg.
	bool prev_name_pattern;
} lexer_t;

void lexer_init(lexer_t* lex, const char* input, uint32_t input_sz);
int lexer_next(lexer_t* lex, token_value* val);
