.TH "aerospike stop" 1 "1 APRIL 2014" "aerospike stop" "aerospike manual" 

.SH NAME

aerospike stop \- stop aerospike server daemon

.SH SYNOPSIS

aerospike stop [--home PATH]

.SH DESCRIPTION

.PP 
Start the aerospike server daemon. The program will assume the current directory is the aerospike home directory. 

To override the home directory, specify the `--home PATH` option.

.SH OPTIONS

.IP "--home PATH"

The directory to use as the aerospike home directory. 

.SH EXAMPLES

.HP
To stop aerospike running in the current directory:

aerospike stop

.HP 
To stop aerospike running a different home directory, such as '/usr/share/aerospike':

aerospike stop --home /usr/share/aerospike