.TH "aerospike start" 1 "1 APRIL 2014" "aerospike start" "aerospike manual" 

.SH NAME

aerospike start \- start aerospike server daemon

.SH SYNOPSIS

aerospike start [--home PATH]

.SH DESCRIPTION

.PP 
Start the aerospike server daemon. The program will assume the current directory is the aerospike home directory. 

To override the home directory, specify the `--home PATH` option.

.SH OPTIONS

.IP "--home PATH"

The directory to use as the aerospike home directory. 

.SH EXAMPLES

.HP
To start aerospike running in the current directory:

aerospike start

.HP 
To start aerospike running a different home directory, such as '/usr/share/aerospike':

aerospike start --home /usr/share/aerospike