#!/bin/bash
################################################################################
#
# Start Script for Aerospike
#
# Inherits definitions from aerospike run script
#
################################################################################

process_stopped() {
  debug "process stopped"
  return 0
}

process_running() {
  debug "process running"
  sudo kill $1
  sudo rm -f $2
  return 0
}

process_died() {
  info "process died abruptly"
  sudo rm -f $2
  return 0
}

main() {

  process_check
  if [ $? -eq 0 ]; then
    info "stopped"
  else
    error "an error occurred"
  fi
}
